### PR TITLE
first version commit

### PR DESCRIPTION
**Pull request by ferishili**
The first version commit to be reviewed.

### CODE REVIEW

**Review by ebbertd — COMMENTED** [review]
@reiferschris and I tested this on our ILIAS 6 testsystem, and it works as expected.
@Amstutz Could you please take a look at the code?

**Review by Amstutz — CHANGES_REQUESTED** [review]
Hi @ferishili 

Thanks for this excellent initial commit. Special thanks for adding a readme. We have been asked to perform a review for this contribution. However, you might want to check back with @ebbertd which changes you really want to implement for a first version of this plugin.

Overall, the code of this plugin is already in good shape, especially considering, that this is your first major contribution to ILIAS. Congrats. Some points are rather hard to anticipate for you. We are aware, that some things lack good documention and are hard to know without some external guidance. 

Please answer the following questions:
- [ ] No Unit Tests: You did not add any Unit Tests, any reason for that? We are aware that most plugins do not add them; however, we believe it to be good practice and something we should improve on in the future.
- [ ] JS Styling: There is a lot of styling going on through JS, is it not possible to use CSS in some of those places? 
- [ ] Legacy Forms: Why did you use the Legacy forms for the plugins and not the new ones from src/UI? Did you miss some Inputs? Note that those legacy components make it hard to test your code.
- [ ] Legacy Tables: Why did you use the Legacy Table for the Representation? Did none of the other components from src/UI fit the needs? What did you miss?
- [ ] Would it be possible to offer a link to the Opencast Video Series in ILIAS, which the inserted video is part of? Might be tricky to get this link…

Please consider the following suggestions. You do not need to follow those, but, but please indicate shortly why you prefer to do otherwise:
- [ ] UI Components: Use the src/UI Components wherever possible (e.g. for Icons). 
- [x] Importants in CSS: Remove the important statements in CSS or explain, why they need to be used.
- [ ] Size of ilObjOpencastEventGUI.php: The class is large, maybe you find some way to refactor this somewhat, and break it into somewhat smaller/testable parts.
- [x] Lng I: Rename Button "Add New Opencast Event" to "Insert selected Opencast Video"
- [x] Lng II: Rename Button "Update Opencast Event" to "Save"
- [ ] Lng III: Option Content Size "Maximum": looks pretty ugly (mainly because of the gray rectangle area)
- [ ] Admin Configs: Possibility to configure the plugins are completely missing (no ConfigGUI). At least there should be:
Default width
Default height
Thumbnail as link to video (similar to the PageComponent-Plugin)
- [x] RBAC: Rights do not get set when an Opencast Event gets created/inserted
- [x] Offline Status: If an Opencast video is set "Offline" this status should be indicated below the title of an open Opencast Event (in red: "Status: Offline")
- [x] Option "Custom": Video should also be responsive when this option is chosen, with the defined size acting as the maximum size.
- [x] Settings I: Get rid of: "Video description", "Reset"-Button, "Cancel"-Button
- [x] Settings II: Add section "Opencast Video", containing information/options:
"Video Title"; New description: "To change the title of the video, go to the Opencast Series which this video is part of."
Direct below: "Replace by different Opencast Video" (OLD: "Select another opencast video from the table")
- [x] Settings IV: Add section "Settings", containing options:
"Online" (OLD: "Online Status"), New description: "If online, participants can view the video."
- [x] Settings V: "Video Size" (OLD: "Content Size"):
"Maximum and responsive"; New description: "Video is displayed as large as possible and can scale down if the user's window is smaller."
"Custom and responsive"; New description: "The defined size acts as a maximum size, while the video can scale down if the user's window is smaller.
- [x] Settings VI: "Thumbnail as link to video"; (OLD: "Display video in a new tab (Full Screen"); New description: "If selected, clicking on the thumbnail will open the video in a new tab. Otherwise, the video is integrated into the page and a click on it starts the video directly."
"Video Identifier"
- [x] Selecting of video: The actual solution of hovering over the table, selecting a video by clicking on it followed by a different color of the selected video is not optimal. First, users can be confused on where to click or how to select a video. Suggestions for optimization:
Insert e tool tip: "Select video by clicking on it" (or similar)
Mark a selected video not gray but green and add a good visible "hook" (for example over the thumbnail).
- [x] Filters: The filters should be shown by default, with the option to hide them. Please save this option for the whole session.

Please implement the following changes:
- [x] PSR-12 Coding style: Please adapt your coding style to PSR 12, see: https://github.com/opencast-ilias/OpenCast/pull/48 and https://github.com/ILIAS-eLearning/ILIAS/pull/4533 (in the last Open Cast meeting we decided to already use PSR in Open Cast devs.).
- [x] JS-Functions in Global Scope: You have JS function in the global scope. This makes the prone for collisions with other functions. Please wrap them. You see a good pattern of how to wrap JS functions in the core code of ILIAS, e.g.: https://github.com/ILIAS-eLearning/ILIAS/blob/release_7/src/UI/templates/js/Table/presentation.js
- [x] Empty JS function: There is an empty JS function (addTitleDescValues), remove this.
- [x] Styling through PHP-Set Classes: Avoid using classes set by PHP for styling, such as "ADDITIONAL_CSS_CLASSES". This makes it hard for designers to see, by only looking at the template, what is going on there. 
- [x] Inline Styling: Avoid inline styles such as height and width or style completely.
- [x] No JS in templates: Remove JS from HTML temples. E.g. in templates/html/tpl.OpencastEventInputSlider.html
- [x] HTML in PHP Code: Remove the HTML from PHP Code, they belong in Template files, e.g. "table_div_replace", or "target_replace"


kindly,
@amstutz with kind support of David Graf and @okaufman

**Comment by ebbertd** [comment]
@ferishili I already the language strings based on the review from @Amstutz

**Comment by ferishili** [comment]
> * Importants in CSS: Remove the important statements in CSS or explain, why they need to be used.

Hi @Amstutz, there were only 2 importants in CSS, where I removed the one on `:hover`, but the other one on `.selected` should be there, because that won't work the way it should otherwise!

**Comment by Amstutz** [comment]
@ferishili : thx for the feedback. Concerning the important on selected, why? Is there some inline styling via js going on I do not see?

**Comment by Amstutz** [comment]
You should be able to beat that with a CSS statement taking a higher precedent than the one from delos, by adding some more classes (no importants), right?

**Comment by ferishili** [comment]
That is true, but I have tried it, it does not work! I am missing something here?

**Comment by reiferschris** [comment]
Hi, I finally got around to test the changes after @Amstutz and @okaufman review (Thank you!) 
While I can not make a qualified comment on the changes to the code I can however comment on the visible changes.

- The filter is enabled by default which is good, however it won't stay that way for the duration of the session. If I reorder the list, reenter the object or reload the page the filter is displayed again.
- I like the new highlighting of the selected video a lot more, the radio buttons are rather small and dangling though. Could those be centered in the line and maybe displayed a little larger?
- the settings for custom size of the video could be improved 
  - 1) 100% should be larger than 640x360, maybe 1920x1080? There is nothing else on those pages anyway, for now at least.
  - 2) step size of 5% should be sufficient IMO.
-  RBAC rights work
- Error handling in case of opencast being offline is better now. Courses don't crash only the event object.
- Offline status is displayed

Thanks @ferishili

**Comment by Amstutz** [comment]
Hi @ferishili while preparing for today's OC meeting I noticed that you requested a further readme of me here some time ago. Sorry for not reacting sooner. I completely missed that. 

Note that we do not have much say in this, since we are not the customer of this new Feature. We can merely voice an opinion. 

If you (or your customer) like me to have another look at it, I can gladly do that. However, I see some checkboxes not yet checked of my review above. So, are all questions answered, or changes applied? 

Thx for some feedback
@Amstutz

**Comment by ferishili** [comment]
Hi @Amstutz, no worries and thanks a lot.
The reasons for remaining items that are not checked:

The main reason I did not go for Unit Test was that, I was not aware of this requirement and also I could not find anything related to unit test and how to do it in the suggested resources and documentation. It would be awesome to include this item into the documentation regarding how to develop an ILIAS plugin.

The reason that I used legacy form for UI was that my initial reference at the time was OpencastPageComponenet plugin and in this plugin no UI Components were used, in addition in the suggested resources only legacy forms are used. Therefore, I was not aware of using UI Components. It would be awesome too have this item into the basics as well.

Another point about not providing the configUI was because we discussed it with Daniel and he told me that for the first version it is not needed, therefore this item could be considered as an enhancement for newer versions.

**Comment by reiferschris** [comment]
Merged despite open change requests because they were not specified in the requirements and the contract is fullfilled. They will however remain on our todo list.

**Pull request merged**
