### PR TITLE
ILIAS 8: preparation

### PR DESCRIPTION
**Pull request by ferishili**
This PR is intended to make the plugin ready for ilias 8 according to the Must-Have package

### Description
The PHPUnit test has been placed, but I was not able to find a way to make it work with the main ilias structure, and came to the conclusion that ILIAS is not yet ready to provide the requirements for the plugins!

### Update
This PR contains the latest required fixes and updates to make it work with v5.6.0 Opencast Series Object Plugin

### CODE REVIEW

**Comment by reiferschris** [comment]
I tested this with plugin version 5.6.0 and ilias 7.26 and it works as expected. Thanks @ferishili

**Review by chfsx — APPROVED** [review]
Hi @ferishili ! The PR looks good to me, thanks a lot (also for thing like replacing $_GET accesses etc.)!

**Comment by dagraf** [comment]
@chfsx: As you already did the review of the PR and aproved it, can you please also merge it? Thx!

**Comment by ferishili** [comment]
Hi @chfsx, would you please do me a favor and merge this PR, so I can continue with further developments.
Thanks in advance

**Pull request merged**
